# Generated by Django 3.1.2 on 2021-01-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
