# Generated by Django 3.1.2 on 2021-01-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210107_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(default='', max_length=200),
        ),
    ]
