# Generated by Django 3.1.2 on 2021-01-08 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210107_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
