# Generated by Django 3.1.2 on 2021-01-08 01:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210107_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('snippet', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
    ]
